compatibility_date = "2023-07-19"
compatibility_flags = ["streams_enable_constructors"]

[[ d1_databases ]]
binding = "DB"
database_name = "synca1-db"
database_id = "f3242c80-2541-4eca-87eb-b3e4304e6ebf"