compatibility_date = "2023-07-19"
compatibility_flags = ["streams_enable_constructors"]

[[ d1_databases ]]
binding = "DB"
database_name = "aiyasan-db"
database_id = "dc03069a-34f8-4651-b647-13a682c7f32c"