compatibility_date = "2023-07-19"
compatibility_flags = ["streams_enable_constructors"]

[[ d1_databases ]]
binding = "DB"
database_name = "aiyasan-db"
database_id = "d1b280b5-1048-4e2c-ac7e-c4d51b0bc4f9"